# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25639171af80ee942cad87f05f56f04298def38d0696d91ed03651f0c3bcdfae4b705903085ffdee89ff8a4350e2474239a5b28f7953ae0baa3a24a94794d34

test:
  secret_key_base: 2ed6cfc1d33a297ace4d6c6f807ac0165df7381be02a6b7355b341d3f3b7ae4b018d4351a413d72f90f9fae43fecbe98d0c92bbadb42dc5a63664b237db67402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
